export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_RICKY_MORTY_DATA_SUCCESS = 'FETCH_RICKY_MORTY_DATA_SUCCESS';
export const FETCH_RICKY_MORTY_DATA_FAIL = 'FETCH_RICKY_MORTY_DATA_FAIL';
export const TRIGGER_FILTER = 'TRIGGER_FILTER';
export const RESET_FILTER = 'RESET_FILTER';
export const DATA_LOADING = 'DATA_LOADING';
export const DATA_LOADED = 'DATA_LOADED';